### ISSUE TITLE
Future plans for Hackers

### ISSUE THREAD

**Issue by weiran** [weiran/Hackers#115]
Apple announced a lot of interesting things at WWDC 2019, including SwiftUI and Combine. Since the keynote I've been thinking about how Hackers could adapt to use those new frameworks, and I think the best way is to do (another) ground up rewrite, like when Swift was introduced. The current codebase has already gone through almost every Swift version migration, and is suffering from some bad choices made back in Swift 1 days. I would also love to integrate some of the features from #100 in this, as well as extracting UltraHN into it's own modern and well maintained Hacker News library for iOS.

This is obviously a big change that will bring little in the way of user benefits initially, but should lay the groundwork for the next few years of iteration on Hackers. But first I want to get one last release on the current codebase out (4.0) that will include everything currently planned.

**Comment by robbiet480** [comment]
Massive +1 on this. Happy to work with you on extracting UltraHN and laying out the new app w/ SwiftUI. I also think that while UltraHN is great, due to changes to the HN HTML it may be best to implement a Hackers server side component which outputs JSON versions of the HTML. Would also obviously improve the notifications story. Obviously there would be a cost associated so unsure about this one...

I also wanted to draw your attention to something else that barely got mentioned at WWDC but might be a great addition: the new [LinkPresentation framework](https://developer.apple.com/documentation/linkpresentation). The docs aren't even up yet (still!) so the best way to get introduced is via [this video](https://developer.apple.com/videos/play/wwdc2019/262/) which was recorded before WWDC.

**Comment by weiran** [comment]
Thanks for the pointer to `LinkPresentation`, it could be viable but it looks like the current implementation creates a `WKWebView` for ever metadata request, which is pretty heavyweight. I've hacked together a branch `apple-link-presentation` which uses this `LinkPresentation` to get thumbnails. It works but with my iPhone SE test device there are clearly frame drops even with image caching. This could be down to my implementation, I'll wait for later betas to try it with.

SwiftUI is still very alpha quality right now, there's no implementation of `SplitViewController` until later seeds for example, so I'm going to leave starting that rewrite until later.
