### ISSUE TITLE
IOS 16? Long comments are truncated

### ISSUE THREAD

**Issue by ssuess** [weiran/Hackers#237]
I recently installed the beta for iOS 16 and have noticed several times that long comments seem to be truncated, ending mid sentence. (Checking other apps like HACK or the web version shows the full comments).

**Comment by weiran** [comment]
A console warning suggests this is caused by iOS 16 falling back to TextKit 1 rendering because of the hit test code for links in comments. But even forcing TextKit 1 for layout doesn't seem to fix this issue in beta 1. Does anyone know if there's an alternative with TextKit 2 to replace `layoutManager. characterIndex(for:in:fractionOfDistanceBetweenInsertionPoints:)` from TextKit 1?

**Comment by weiran** [comment]
iOS 16 beta 2 partially fixes this - it no longer truncates comments when falling back to TextKit 1 but there are still glitchy layout changes.

**Comment by weiran** [comment]
I just tried this on the latest beta 5 and it seems fully resolved now.

**Comment by JeffreyCA** [comment]
I'm on 16.1 (20B5045d) and it looks like long URLs are getting truncated and tapping on them navigates to the truncated URL instead of the actual one.

Example article: https://news.ycombinator.com/item?id=32911299
