### ISSUE TITLE
Space Usage

### ISSUE THREAD

**Issue by ballwood** [weiran/Hackers#254]
@weiran Just had a look at my iPhone and seems the hackers app is taking up 1GB of space? Seems awfully high…Is it caching to disk or something and not being cleared? 

If you have any idea point me to the code and I’ll do a PR to fix it, cheers!

**Comment by ballwood** [comment]
Closing as didn’t see the other issue! Will have a look at the icons.

**Comment by weiran** [comment]
Yep same issue as #219, but I'm no longer sure the cause is the image caching. 

If you have time I'd appreciate if you could export the app container from your phone in Xcode, and see where the disk usage is coming from? Nuke image cache should be in `Library/Caches/com.weiranzhang.Hackers/com.github.kean.Nuke.Cache`

I recently upgraded my phone so my only has 20MB in it.
